### Module 2: Structured Data (Pandas Essentials)
#### Lesson 1: Series vs. DataFrames

In [1]:
import pandas as pd

In [2]:
ages = [22, 25, 64, 21, 30]
age_series = pd.Series(ages)

In [3]:
age_series

0    22
1    25
2    64
3    21
4    30
dtype: int64

In [4]:
age_series[2]

np.int64(64)

In [5]:
patient_names = ["John", "Jane", "Doe", "Smith", "Emily"]
age_series = pd.Series(ages, index=patient_names)
age_series

John     22
Jane     25
Doe      64
Smith    21
Emily    30
dtype: int64

In [6]:
age_series["Doe"]

np.int64(64)

In [7]:
hospital_data = {
    "Age": [22, 25, 64, 21, 30],
    "Blood Pressure": [120, 130, 140, 110, 125],
    "Room Number": [101, 102, 103, 104, 105]
}

hospital_df = pd.DataFrame(hospital_data, index=patient_names)
hospital_df

       Age  Blood Pressure  Room Number
John    22             120          101
Jane    25             130          102
Doe     64             140          103
Smith   21             110          104
Emily   30             125          105

In [8]:
hospital_df = pd.DataFrame(hospital_data)
hospital_df

   Age  Blood Pressure  Room Number
0   22             120          101
1   25             130          102
2   64             140          103
3   21             110          104
4   30             125          105

In [9]:
hospital_df["Age"]

0    22
1    25
2    64
3    21
4    30
Name: Age, dtype: int64

##### Lab: Department Inventory

1. Create a **DataFrame** called `dept_df`.

2. The columns should be:

    * `Staff_Count: [15, 8, 22, 12]`

    * `Budget: [50000, 25000, 100000, 45000]`

    * `Critical_Care: [True, False, True, False]`

3. The Index (Row Names) should be: `["ER", "Pharmacy", "Surgery", "Radiology"]`.

4. **The "Extraction":** Extract only the `Budget` column from your DataFrame. What is the type of the result? (Check it with `type()`).

5. **The "Math":** Using the vectorization skills you learned in NumPy, multiply the `Staff_Count` column by `1.1` (representing a 10% staff increase).

#### Lesson 2: Smart Importing & Data Inspection

In [18]:
import pandas as pd

file_path = r"data\full-hospital-data-files\patients.csv"
patients_df = pd.read_csv(file_path)

In [19]:
patients_df

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,231a2cb1-0ebe-dc12-3c96-f625d795ef3a,1992-07-29,NaN,999-40-5904,S99939861,X73004803X,Mr.,Bill567,Wolf938,NaN,...,Wellesley Massachusetts US,983 Smith Arcade,Boston,Massachusetts,Suffolk County,2134.0,42.245182,-71.055145,9.013664e+05,8227.1175
1,9b5de0da-9c38-3584-acd7-98f03f3177d4,1980-09-14,NaN,999-94-8451,S99920404,X8777516X,Mrs.,Gwyneth692,Koch169,NaN,...,Abington Massachusetts US,1037 Bins Quay,Falmouth,Massachusetts,Barnstable County,2540.0,41.603362,-70.628755,1.508463e+06,148114.7235
2,34c9600a-6f70-b552-96bc-f751024f8746,2002-04-07,NaN,999-93-1486,S99996416,NaN,Mr.,Víctor493,Rentería94,NaN,...,Mexico City Mexico City MX,703 Zulauf Rest Apt 78,Winchendon,Massachusetts,Worcester County,1475.0,42.696234,-72.074439,5.182007e+05,1644.9450
3,12aabca7-b8e1-a2a7-7e23-08b1c01a82bb,1955-06-18,NaN,999-37-4256,S99935259,X73306558X,Mrs.,Ramona980,Toledo81,NaN,...,Panama City Panama PA,486 O'Conner Corner,Milford,Massachusetts,Worcester County,NaN,42.122622,-71.483149,1.167983e+06,373165.6810
4,8825ff6d-ee2d-40b1-a0ad-fdca3ead2fc7,1963-01-21,NaN,999-40-2211,S99982807,X80006334X,Mr.,Jere230,Herzog843,NaN,...,Burlington Massachusetts US,1035 Kohler Path Unit 82,Springfield,Massachusetts,Hampden County,1118.0,42.058813,-72.559275,1.518577e+06,1016.9775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6033,342370b4-dd6f-798c-e023-70172d115b29,1928-12-16,2016-03-18,999-46-3585,S99917822,X71467855X,Mrs.,Anika194,Huel628,NaN,...,Worcester Massachusetts US,654 Crona Heights,Duxbury,Massachusetts,Plymouth County,2332.0,42.087218,-70.657163,2.564785e+06,801484.6910
6034,5759324d-21a9-c8d6-0d99-3c38d7c67af4,1928-12-16,2013-12-24,999-75-9781,S99919361,X82069789X,Mrs.,Rebbecca977,Parker433,NaN,...,Lynn Massachusetts US,317 Russel Ranch,Duxbury,Massachusetts,Plymouth County,2332.0,42.093906,-70.683214,2.208034e+06,910402.6665
6035,6a06fbe3-3c8d-7ae1-3229-9fd190894558,1928-12-16,2020-03-11,999-84-2838,S99982623,X88205966X,Mrs.,Leanne251,Altenwerth646,NaN,...,Springfield Massachusetts US,310 Paucek Port,Duxbury,Massachusetts,Plymouth County,NaN,42.087696,-70.698342,2.818387e+06,626246.0675
6036,fbbfd86e-9508-46b9-ca58-7f7118acd882,1934-07-31,2018-09-20,999-32-6991,S99928201,X21306009X,Mrs.,Jena102,Kilback373,NaN,...,Hamilton Massachusetts US,454 Koepp Knoll Suite 84,Duxbury,Massachusetts,Plymouth County,2332.0,42.076204,-70.723114,3.283049e+06,253123.8515
6037,ea8d1364-2fe4-f4cc-7979-e959537f5117,1934-07-31,NaN,999-11-5288,S99926682,X67027903X,Mrs.,Roxie199,Volkman526,NaN,...,Peabody Massachusetts US,549 Erdman Course,Duxbury,Massachusetts,Plymouth County,2332.0,42.022597,-70.700534,3.138072e+06,351268.4945

In [20]:
patients_df.shape

(6038, 25)

In [21]:
patients_df.columns

Index(['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX',
       'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY',
       'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP',
       'LAT', 'LON', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE'],
      dtype='str')

In [22]:
patients_df.dtypes

Id                         str
BIRTHDATE                  str
DEATHDATE                  str
SSN                        str
DRIVERS                    str
PASSPORT                   str
PREFIX                     str
FIRST                      str
LAST                       str
SUFFIX                     str
MAIDEN                     str
MARITAL                    str
RACE                       str
ETHNICITY                  str
GENDER                     str
BIRTHPLACE                 str
ADDRESS                    str
CITY                       str
STATE                      str
COUNTY                     str
ZIP                    float64
LAT                    float64
LON                    float64
HEALTHCARE_EXPENSES    float64
HEALTHCARE_COVERAGE    float64
dtype: object

In [23]:
patients_df.head()

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,231a2cb1-0ebe-dc12-3c96-f625d795ef3a,1992-07-29,NaN,999-40-5904,S99939861,X73004803X,Mr.,Bill567,Wolf938,NaN,...,Wellesley Massachusetts US,983 Smith Arcade,Boston,Massachusetts,Suffolk County,2134.0,42.245182,-71.055145,9.013664e+05,8227.1175
1,9b5de0da-9c38-3584-acd7-98f03f3177d4,1980-09-14,NaN,999-94-8451,S99920404,X8777516X,Mrs.,Gwyneth692,Koch169,NaN,...,Abington Massachusetts US,1037 Bins Quay,Falmouth,Massachusetts,Barnstable County,2540.0,41.603362,-70.628755,1.508463e+06,148114.7235
2,34c9600a-6f70-b552-96bc-f751024f8746,2002-04-07,NaN,999-93-1486,S99996416,NaN,Mr.,Víctor493,Rentería94,NaN,...,Mexico City Mexico City MX,703 Zulauf Rest Apt 78,Winchendon,Massachusetts,Worcester County,1475.0,42.696234,-72.074439,5.182007e+05,1644.9450
3,12aabca7-b8e1-a2a7-7e23-08b1c01a82bb,1955-06-18,NaN,999-37-4256,S99935259,X73306558X,Mrs.,Ramona980,Toledo81,NaN,...,Panama City Panama PA,486 O'Conner Corner,Milford,Massachusetts,Worcester County,NaN,42.122622,-71.483149,1.167983e+06,373165.6810
4,8825ff6d-ee2d-40b1-a0ad-fdca3ead2fc7,1963-01-21,NaN,999-40-2211,S99982807,X80006334X,Mr.,Jere230,Herzog843,NaN,...,Burlington Massachusetts US,1035 Kohler Path Unit 82,Springfield,Massachusetts,Hampden County,1118.0,42.058813,-72.559275,1.518577e+06,1016.9775

In [24]:
patients_df.tail()

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
6033,342370b4-dd6f-798c-e023-70172d115b29,1928-12-16,2016-03-18,999-46-3585,S99917822,X71467855X,Mrs.,Anika194,Huel628,NaN,...,Worcester Massachusetts US,654 Crona Heights,Duxbury,Massachusetts,Plymouth County,2332.0,42.087218,-70.657163,2.564785e+06,801484.6910
6034,5759324d-21a9-c8d6-0d99-3c38d7c67af4,1928-12-16,2013-12-24,999-75-9781,S99919361,X82069789X,Mrs.,Rebbecca977,Parker433,NaN,...,Lynn Massachusetts US,317 Russel Ranch,Duxbury,Massachusetts,Plymouth County,2332.0,42.093906,-70.683214,2.208034e+06,910402.6665
6035,6a06fbe3-3c8d-7ae1-3229-9fd190894558,1928-12-16,2020-03-11,999-84-2838,S99982623,X88205966X,Mrs.,Leanne251,Altenwerth646,NaN,...,Springfield Massachusetts US,310 Paucek Port,Duxbury,Massachusetts,Plymouth County,NaN,42.087696,-70.698342,2.818387e+06,626246.0675
6036,fbbfd86e-9508-46b9-ca58-7f7118acd882,1934-07-31,2018-09-20,999-32-6991,S99928201,X21306009X,Mrs.,Jena102,Kilback373,NaN,...,Hamilton Massachusetts US,454 Koepp Knoll Suite 84,Duxbury,Massachusetts,Plymouth County,2332.0,42.076204,-70.723114,3.283049e+06,253123.8515
6037,ea8d1364-2fe4-f4cc-7979-e959537f5117,1934-07-31,NaN,999-11-5288,S99926682,X67027903X,Mrs.,Roxie199,Volkman526,NaN,...,Peabody Massachusetts US,549 Erdman Course,Duxbury,Massachusetts,Plymouth County,2332.0,42.022597,-70.700534,3.138072e+06,351268.4945

In [25]:
patients_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6038 entries, 0 to 6037
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   6038 non-null   str
 1   BIRTHDATE            6038 non-null   str
 2   DEATHDATE            1038 non-null   str
 3   SSN                  6038 non-null   str
 4   DRIVERS              5106 non-null   str
 5   PASSPORT             4823 non-null   str
 6   PREFIX               4955 non-null   str
 7   FIRST                6038 non-null   str
 8   LAST                 6038 non-null   str
 9   SUFFIX               97 non-null     str
 10  MAIDEN               1705 non-null   str
 11  MARITAL              4241 non-null   str
 12  RACE                 6038 non-null   str
 13  ETHNICITY            6038 non-null   str
 14  GENDER               6038 non-null   str
 15  BIRTHPLACE           6038 non-null   str
 16  ADDRESS              6038 non-null   str
 17  CITY                 6038 non-null   str
 18  STATE                6038 non-null   str
 19  COUNTY               6038 non-null   str
 20  ZIP                  3241 non-null   float64
 21  LAT                  6038 non-null   float64
 22  LON                  6038 non-null   float64
 23  HEALTHCARE_EXPENSES  6038 non-null   float64
 24  HEALTHCARE_COVERAGE  6038 non-null   float64
dtypes: float64(5), str(20)
memory usage: 1.2 MB

In [26]:
patients_df.describe()

,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
count,3241.000000,6038.000000,6038.000000,6.038000e+03,6.038000e+03
mean,2004.806541,42.267070,-71.358588,1.253098e+06,1.819016e+05
std,445.199952,0.284124,0.625357,9.690295e+05,3.750270e+05
min,1001.000000,41.251677,-73.487414,1.889108e+03,0.000000e+00
25%,1803.000000,42.119264,-71.567013,4.537897e+05,1.571964e+03
50%,2118.000000,42.309040,-71.156030,1.207136e+06,2.642932e+04
75%,2215.000000,42.449215,-71.014008,1.868730e+06,2.288944e+05
max,2861.000000,42.896964,-69.933807,2.171109e+07,9.759952e+06

In [27]:
patients_df = pd.read_csv(
    file_path,
    parse_dates=["BIRTHDATE", "DEATHDATE"],
    usecols=["SSN", "BIRTHDATE", "DEATHDATE", "GENDER"]
)

patients_df

      BIRTHDATE  DEATHDATE          SSN GENDER
0    1992-07-29        NaT  999-40-5904      M
1    1980-09-14        NaT  999-94-8451      F
2    2002-04-07        NaT  999-93-1486      M
3    1955-06-18        NaT  999-37-4256      F
4    1963-01-21        NaT  999-40-2211      M
...         ...        ...          ...    ...
6033 1928-12-16 2016-03-18  999-46-3585      F
6034 1928-12-16 2013-12-24  999-75-9781      F
6035 1928-12-16 2020-03-11  999-84-2838      F
6036 1934-07-31 2018-09-20  999-32-6991      F
6037 1934-07-31        NaT  999-11-5288      F

[6038 rows x 4 columns]

In [28]:
patients_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6038 entries, 0 to 6037
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BIRTHDATE  6038 non-null   datetime64[us]
 1   DEATHDATE  1038 non-null   datetime64[us]
 2   SSN        6038 non-null   str
 3   GENDER     6038 non-null   str
dtypes: datetime64[us](2), str(2)
memory usage: 188.8 KB

##### Lab: The Hospital Audit

Now, let's look at the `encounters.csv` file (this tracks every time a patient visits the hospital).

1. Load the full `encounters.csv` file.

2. How many rows and columns are in this file?

3. Identify one column that contains **Missing Values** (Nulls).

4. From column `TOTAL_CLAIM_COST`

    * What is the **average (mean)** cost of a hospital visit?

    * What was the **maximum** cost recorded?

5. **Memory Check:** How much memory (KB/MB) is this DataFrame using?

#### Lesson 3: Indexing, Selection, and Slicing

In [37]:
import pandas as pd
file_path = r"data\full-hospital-data-files\patients.csv"
patients_df = pd.read_csv(
    file_path,
    usecols=["SSN", "BIRTHDATE", "DEATHDATE", "FIRST", "GENDER", "HEALTHCARE_EXPENSES", "HEALTHCARE_COVERAGE"]
)
patients_df

,BIRTHDATE,DEATHDATE,SSN,FIRST,GENDER,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,1992-07-29,NaN,999-40-5904,Bill567,M,9.013664e+05,8227.1175
1,1980-09-14,NaN,999-94-8451,Gwyneth692,F,1.508463e+06,148114.7235
2,2002-04-07,NaN,999-93-1486,Víctor493,M,5.182007e+05,1644.9450
3,1955-06-18,NaN,999-37-4256,Ramona980,F,1.167983e+06,373165.6810
4,1963-01-21,NaN,999-40-2211,Jere230,M,1.518577e+06,1016.9775
...,...,...,...,...,...,...,...
6033,1928-12-16,2016-03-18,999-46-3585,Anika194,F,2.564785e+06,801484.6910
6034,1928-12-16,2013-12-24,999-75-9781,Rebbecca977,F,2.208034e+06,910402.6665
6035,1928-12-16,2020-03-11,999-84-2838,Leanne251,F,2.818387e+06,626246.0675
6036,1934-07-31,2018-09-20,999-32-6991,Jena102,F,3.283049e+06,253123.8515
6037,1934-07-31,NaN,999-11-5288,Roxie199,F,3.138072e+06,351268.4945

In [38]:
# iloc, loc, shorthand
# iloc[row_index, col_index]
patients_df.iloc[0, 0]

'1992-07-29'

In [39]:
patients_df.iloc[0, 2:5]

SSN       999-40-5904
FIRST         Bill567
GENDER              M
Name: 0, dtype: object

In [40]:
type(patients_df.iloc[0, 2:5])

pandas.Series

In [41]:
patients_df.iloc[:5, 2:5]

           SSN       FIRST GENDER
0  999-40-5904     Bill567      M
1  999-94-8451  Gwyneth692      F
2  999-93-1486   Víctor493      M
3  999-37-4256   Ramona980      F
4  999-40-2211     Jere230      M

In [42]:
type(patients_df.iloc[:5, 2:5])

pandas.DataFrame

In [43]:
# loc[row_label, col_label]
patients_df.loc[0, "BIRTHDATE"]

'1992-07-29'

In [46]:
patients_df.loc[:5, "SSN":"GENDER"]

           SSN       FIRST GENDER
0  999-40-5904     Bill567      M
1  999-94-8451  Gwyneth692      F
2  999-93-1486   Víctor493      M
3  999-37-4256   Ramona980      F
4  999-40-2211     Jere230      M
5  999-90-9807  Mariann762      F

In [47]:
# Shorthand
patients_df["BIRTHDATE"]

0       1992-07-29
1       1980-09-14
2       2002-04-07
3       1955-06-18
4       1963-01-21
           ...
6033    1928-12-16
6034    1928-12-16
6035    1928-12-16
6036    1934-07-31
6037    1934-07-31
Name: BIRTHDATE, Length: 6038, dtype: str

In [48]:
patients_df[["BIRTHDATE", "SSN", "GENDER", "FIRST"]]

       BIRTHDATE          SSN GENDER        FIRST
0     1992-07-29  999-40-5904      M      Bill567
1     1980-09-14  999-94-8451      F   Gwyneth692
2     2002-04-07  999-93-1486      M    Víctor493
3     1955-06-18  999-37-4256      F    Ramona980
4     1963-01-21  999-40-2211      M      Jere230
...          ...          ...    ...          ...
6033  1928-12-16  999-46-3585      F     Anika194
6034  1928-12-16  999-75-9781      F  Rebbecca977
6035  1928-12-16  999-84-2838      F    Leanne251
6036  1934-07-31  999-32-6991      F      Jena102
6037  1934-07-31  999-11-5288      F     Roxie199

[6038 rows x 4 columns]

In [50]:
patients_df[:5]

,BIRTHDATE,DEATHDATE,SSN,FIRST,GENDER,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,1992-07-29,NaN,999-40-5904,Bill567,M,9.013664e+05,8227.1175
1,1980-09-14,NaN,999-94-8451,Gwyneth692,F,1.508463e+06,148114.7235
2,2002-04-07,NaN,999-93-1486,Víctor493,M,5.182007e+05,1644.9450
3,1955-06-18,NaN,999-37-4256,Ramona980,F,1.167983e+06,373165.6810
4,1963-01-21,NaN,999-40-2211,Jere230,M,1.518577e+06,1016.9775

In [54]:
mask = patients_df["HEALTHCARE_EXPENSES"] < 5000
patients_df[mask]["SSN"]

695     999-58-6055
737     999-11-6173
2361    999-24-9696
3348    999-46-1815
4187    999-57-3722
4573    999-41-3653
5036    999-80-1699
5053    999-41-3164
5248    999-16-2977
5612    999-20-5426
5770    999-80-9550
Name: SSN, dtype: str

##### Lab: Hospital More Audit

1. Load `encounters.csv`.
2. Filter the data to find rows where the `ENCOUNTERCLASS` is `'ambulatory'`, the `TOTAL_CLAIM_COST` is over `120`, and the `PAYER_COVERAGE` is under `50`.
3. From that filtered result, create a new DataFrame that contains only the `START`, `STOP`, `PATIENT`, and `TOTAL_CLAIM_COST` columns.
4. Set the `PATIENT` ID as the index.
5. Extract the `TOTAL_CLAIM_COST` for the **first** patient in your filtered list using the **indexer that handles labels**.
6. Calculate the average `TOTAL_CLAIM_COST` of this final group.