### Module 3: Data Cleaning & Preprocessing
#### Lesson 1: Managing Missing Data (The NaN Problem)

In [29]:
import pandas as pd
import numpy as np

data = {
    'Date': pd.to_datetime(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04', '2026-01-05']),
    'Patient_ID': [101, 101, np.nan, 101, 101],
    'Heart_Rate': [72, np.nan, np.nan, 85, np.nan],
    'Notes': [np.nan, "Stable", np.nan, "Recovering", np.nan],
    'Empty_Col': [np.nan, np.nan, np.nan, np.nan, np.nan] # All missing
}

df = pd.DataFrame(data)
print("Original Messy Data:")
df

Original Messy Data:

        Date  Patient_ID  Heart_Rate       Notes  Empty_Col
0 2026-01-01       101.0        72.0         NaN        NaN
1 2026-01-02       101.0         NaN      Stable        NaN
2 2026-01-03         NaN         NaN         NaN        NaN
3 2026-01-04       101.0        85.0  Recovering        NaN
4 2026-01-05       101.0         NaN         NaN        NaN

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        5 non-null      datetime64[us]
 1   Patient_ID  4 non-null      float64
 2   Heart_Rate  2 non-null      float64
 3   Notes       2 non-null      str
 4   Empty_Col   0 non-null      float64
dtypes: datetime64[us](1), float64(3), str(1)
memory usage: 332.0 bytes

In [32]:
df.isnull().sum()

Date          0
Patient_ID    1
Heart_Rate    3
Notes         3
Empty_Col     5
dtype: int64

In [33]:
df.dropna()

Empty DataFrame
Columns: [Date, Patient_ID, Heart_Rate, Notes, Empty_Col]
Index: []

In [34]:
df.dropna(thresh=3)

        Date  Patient_ID  Heart_Rate       Notes  Empty_Col
0 2026-01-01       101.0        72.0         NaN        NaN
1 2026-01-02       101.0         NaN      Stable        NaN
3 2026-01-04       101.0        85.0  Recovering        NaN

In [35]:
df.dropna(subset=['Patient_ID', 'Heart_Rate'])

        Date  Patient_ID  Heart_Rate       Notes  Empty_Col
0 2026-01-01       101.0        72.0         NaN        NaN
3 2026-01-04       101.0        85.0  Recovering        NaN

In [36]:
df.dropna(axis=1)

        Date
0 2026-01-01
1 2026-01-02
2 2026-01-03
3 2026-01-04
4 2026-01-05

In [37]:
df.dropna(axis=1, how="all")

        Date  Patient_ID  Heart_Rate       Notes
0 2026-01-01       101.0        72.0         NaN
1 2026-01-02       101.0         NaN      Stable
2 2026-01-03         NaN         NaN         NaN
3 2026-01-04       101.0        85.0  Recovering
4 2026-01-05       101.0         NaN         NaN

In [39]:
df

        Date  Patient_ID  Heart_Rate       Notes  Empty_Col
0 2026-01-01       101.0        72.0         NaN        NaN
1 2026-01-02       101.0         NaN      Stable        NaN
2 2026-01-03         NaN         NaN         NaN        NaN
3 2026-01-04       101.0        85.0  Recovering        NaN
4 2026-01-05       101.0         NaN         NaN        NaN

In [40]:
df.fillna("Unknown")

        Date Patient_ID Heart_Rate       Notes Empty_Col
0 2026-01-01      101.0       72.0     Unknown   Unknown
1 2026-01-02      101.0    Unknown      Stable   Unknown
2 2026-01-03    Unknown    Unknown     Unknown   Unknown
3 2026-01-04      101.0       85.0  Recovering   Unknown
4 2026-01-05      101.0    Unknown     Unknown   Unknown

In [42]:
df.fillna({'Patient_ID': 101, 'Notes': "Unknown"})

        Date  Patient_ID  Heart_Rate       Notes  Empty_Col
0 2026-01-01       101.0        72.0     Unknown        NaN
1 2026-01-02       101.0         NaN      Stable        NaN
2 2026-01-03       101.0         NaN     Unknown        NaN
3 2026-01-04       101.0        85.0  Recovering        NaN
4 2026-01-05       101.0         NaN     Unknown        NaN

In [43]:
df

        Date  Patient_ID  Heart_Rate       Notes  Empty_Col
0 2026-01-01       101.0        72.0         NaN        NaN
1 2026-01-02       101.0         NaN      Stable        NaN
2 2026-01-03         NaN         NaN         NaN        NaN
3 2026-01-04       101.0        85.0  Recovering        NaN
4 2026-01-05       101.0         NaN         NaN        NaN

In [44]:
df.fillna({'Patient_ID': 101, 'Notes': "Unknown"}, inplace=True)

        Date  Patient_ID  Heart_Rate       Notes  Empty_Col
0 2026-01-01       101.0        72.0     Unknown        NaN
1 2026-01-02       101.0         NaN      Stable        NaN
2 2026-01-03       101.0         NaN     Unknown        NaN
3 2026-01-04       101.0        85.0  Recovering        NaN
4 2026-01-05       101.0         NaN     Unknown        NaN

In [45]:
df

        Date  Patient_ID  Heart_Rate       Notes  Empty_Col
0 2026-01-01       101.0        72.0     Unknown        NaN
1 2026-01-02       101.0         NaN      Stable        NaN
2 2026-01-03       101.0         NaN     Unknown        NaN
3 2026-01-04       101.0        85.0  Recovering        NaN
4 2026-01-05       101.0         NaN     Unknown        NaN

In [46]:
df.ffill()

        Date  Patient_ID  Heart_Rate       Notes  Empty_Col
0 2026-01-01       101.0        72.0     Unknown        NaN
1 2026-01-02       101.0        72.0      Stable        NaN
2 2026-01-03       101.0        72.0     Unknown        NaN
3 2026-01-04       101.0        85.0  Recovering        NaN
4 2026-01-05       101.0        85.0     Unknown        NaN

In [47]:
df.bfill()

        Date  Patient_ID  Heart_Rate       Notes  Empty_Col
0 2026-01-01       101.0        72.0     Unknown        NaN
1 2026-01-02       101.0        85.0      Stable        NaN
2 2026-01-03       101.0        85.0     Unknown        NaN
3 2026-01-04       101.0        85.0  Recovering        NaN
4 2026-01-05       101.0         NaN     Unknown        NaN

In [48]:
df.ffill(limit=1)

        Date  Patient_ID  Heart_Rate       Notes  Empty_Col
0 2026-01-01       101.0        72.0     Unknown        NaN
1 2026-01-02       101.0        72.0      Stable        NaN
2 2026-01-03       101.0         NaN     Unknown        NaN
3 2026-01-04       101.0        85.0  Recovering        NaN
4 2026-01-05       101.0        85.0     Unknown        NaN

##### Lab: The Patient Data Cleanup

Use the `patients.csv` file for this task. This is a real-world scenario where administrative data is incomplete.

**Task 1: The Audit**
    
* Load `patients.csv`.
* Print the count of null values for **every column**.
    
**Task 2: Simple Filling**
    
* Fill the missing values in the `MARITAL` column with 'U' (Unknown).
    
**Task 3: The Conditional Prefix Engine**

This is the core of the exercise. You need to fill the `PREFIX` column based on these specific rules:

| Gender | Marital Status | Target Prefix |
|--------|---|---|
| M | Any | MR |
| F | M (Married) | MRS |
| F | S or U (Single/Unknown) | MS |

**Constraints:**

* Only fill the value if PREFIX is currently `null`.
* Do not use a for loop (it's too slow for large datasets).