### Module 2: Structured Data (Pandas Essentials)
#### Lesson 1: Series vs. DataFrames

In [1]:
import pandas as pd

In [2]:
ages = [22, 25, 64, 21, 30]
age_series = pd.Series(ages)

In [3]:
age_series

0    22
1    25
2    64
3    21
4    30
dtype: int64

In [4]:
age_series[2]

np.int64(64)

In [5]:
patient_names = ["John", "Jane", "Doe", "Smith", "Emily"]
age_series = pd.Series(ages, index=patient_names)
age_series

John     22
Jane     25
Doe      64
Smith    21
Emily    30
dtype: int64

In [6]:
age_series["Doe"]

np.int64(64)

In [7]:
hospital_data = {
    "Age": [22, 25, 64, 21, 30],
    "Blood Pressure": [120, 130, 140, 110, 125],
    "Room Number": [101, 102, 103, 104, 105]
}

hospital_df = pd.DataFrame(hospital_data, index=patient_names)
hospital_df

       Age  Blood Pressure  Room Number
John    22             120          101
Jane    25             130          102
Doe     64             140          103
Smith   21             110          104
Emily   30             125          105

In [8]:
hospital_df = pd.DataFrame(hospital_data)
hospital_df

   Age  Blood Pressure  Room Number
0   22             120          101
1   25             130          102
2   64             140          103
3   21             110          104
4   30             125          105

In [9]:
hospital_df["Age"]

0    22
1    25
2    64
3    21
4    30
Name: Age, dtype: int64

##### Lab: Department Inventory

1. Create a **DataFrame** called `dept_df`.

2. The columns should be:

    * `Staff_Count: [15, 8, 22, 12]`

    * `Budget: [50000, 25000, 100000, 45000]`

    * `Critical_Care: [True, False, True, False]`

3. The Index (Row Names) should be: `["ER", "Pharmacy", "Surgery", "Radiology"]`.

4. **The "Extraction":** Extract only the `Budget` column from your DataFrame. What is the type of the result? (Check it with `type()`).

5. **The "Math":** Using the vectorization skills you learned in NumPy, multiply the `Staff_Count` column by `1.1` (representing a 10% staff increase).